name: Build & Deploy to IIS

on:
  push:
    branches: [ "main" ]  

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      # 1. Lấy code
      - name: Checkout source
        uses: actions/checkout@v4

      # 2. Cài .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0  

      # 3. Restore NuGet packages
      - name: Restore dependencies
        run: dotnet restore

      # 6. Publish ra thư mục ./publish
      - name: Publish
        run: dotnet publish ./FPTTrackingSystem/FPTTrackingSystem.csproj -c Release -r win-x64 --self-contained true -o ./publish
     
      - name: Deploy to IIS via PowerShell
        shell: pwsh
        run: |
          # Tạo credential từ secrets
          $user = "${{ secrets.VPS_USER }}"
          $pass = ConvertTo-SecureString "${{ secrets.VPS_PASS }}" -AsPlainText -Force
          $cred = New-Object System.Management.Automation.PSCredential ($user, $pass)
      
          # Kết nối WinRM tới server IIS
          $session = New-PSSession -ComputerName ${{ secrets.VPS_HOST }} -Credential $cred
      
          # Thực thi deploy trên server
          Invoke-Command -Session $session -ScriptBlock {
              $target = "C:\Users\Administrator\Desktop\Publish-BE"
      
              # Xoá file cũ
              Remove-Item "$target\*" -Recurse -Force
      
              # Copy file mới từ thư mục publish
              Copy-Item "\\runner\_work\myapp\publish\*" $target -Recurse -Force
      
              # Restart IIS
              iisreset
          }
      
          # Đóng session
          Remove-PSSession $session
